### ISSUE TITLE
Wait For Email: UID SEARCH Failure due to backend error

### ISSUE THREAD

**Issue by bobmeliev** [rickypc/robotframework-imaplibrary#23]
Wait For Email is failing if specify sender argument.

`${latest}=    Wait For Email    subject=Welcome!    timeout=30
`

Works fine but if you specify sender then it starts failing.

`${latest}=    Wait For Email    sender=noreply@example.com    subject=Welcome!    timeout=30`

Fails with error:

> FAIL : imap.search error: NO, [b'[UNAVAILABLE] UID SEARCH Failure due to backend error.

I'm using @lasselindqvist ImapLibrary2 as it has the latest changes but unfortunately couldn't report the issue there.

**Comment by lasselindqvist** [comment]
I have now enabled issues in the fork: https://github.com/lasselindqvist/robotframework-imaplibrary2/issues

**Comment by bobmeliev** [comment]
Thanks @lasselindqvist I will move the issues to your repository.

**Comment by bobmeliev** [comment]
Issue is moved to https://github.com/lasselindqvist/robotframework-imaplibrary2/issues/2
